In [2]:
import numpy as np

 # numpy arrays come in 2 flavours:
 # vectors --> 1d shapes
 # matrices --> 2d shapes
    
my_lst = [1,2,3]
arr = np.array(my_lst)
print(arr)

[1 2 3]


In [2]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
arr2 = np.array(my_mat)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
### common ways to create a numpy array ###
numpy_range = np.arange(0,10,3) # works like python 'range' function
print(numpy_range)

[0 3 6 9]


In [4]:
numpy_zeros = np.zeros((5,7))
print(numpy_zeros)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [5]:
### Evenly spaced output ###
numpy_linspace = np.linspace(0,5,25) # different than range
print(numpy_linspace)

[ 0.          0.20833333  0.41666667  0.625       0.83333333  1.04166667
  1.25        1.45833333  1.66666667  1.875       2.08333333  2.29166667
  2.5         2.70833333  2.91666667  3.125       3.33333333  3.54166667
  3.75        3.95833333  4.16666667  4.375       4.58333333  4.79166667
  5.        ]


In [4]:
### identity matrix ###
numpy_id_matrix = np.eye(3)
print(numpy_id_matrix)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [7]:
### random numbers ###
numpy_random = np.random.rand(5,5)
print(numpy_random)

[[ 0.82247438  0.66666374  0.50259684  0.56973005  0.56335117]
 [ 0.12438014  0.28620905  0.49789319  0.94418855  0.92074564]
 [ 0.68607912  0.81742229  0.92113316  0.58473219  0.64880518]
 [ 0.65279371  0.51856063  0.52407683  0.57715056  0.43339166]
 [ 0.55896314  0.24241241  0.89426622  0.05142719  0.56318471]]


In [8]:
numpy_random_gaussian = np.random.randn(5,5)
print(numpy_random_gaussian)

[[ 2.21960447  0.08108087 -0.03616002  0.1101119  -1.2222528 ]
 [-0.2700106  -1.01626506  0.26420509  1.07806709  1.28574783]
 [-0.72552312  0.76332179  0.31546146  0.31154592 -0.45471921]
 [ 0.28658855 -1.11255005  0.01294503  1.28291469  0.6963079 ]
 [ 2.84659678  0.77188485 -0.79658173 -1.01792975 -1.06294638]]


In [9]:
numpy_random_random = np.random.randint(0,100,50)
print(numpy_random_random)

[46 31  2 84  7 78 58 86 41 48 71  6 53 38  2 74 91 38 29 18 11 71 81 67  4
 74 12 52 36 74 35 24 97 45 62 46 44 16 75 66 85 41 88 32 57  3 19 61 58 52]


In [19]:
### Shaping the matrix ###
arr = np.arange(25)
numpy_reshape = arr.reshape(5,5)
print(numpy_reshape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [11]:
numpy_random_random = np.random.randint(0,100,50)
print("Min is:")
print(numpy_random_random.argmin())
print("Max is:")
print(numpy_random_random.argmax())

Min is:
19
Max is:
4


In [12]:
numpy_random_random = np.random.randint(0,100,50)
print(numpy_random_random.shape)
print(numpy_random_random.dtype)

(50,)
int32


In [25]:
# Samples are uniformly distributed over the half-open interval [low, high) (includes low, but excludes high). 
# In other words, any value within the given interval is equally likely to be drawn by uniform.
np.random.uniform(-100, 100, size=(2,3)) #

array([[-75.5200335 ,  95.40728171, -54.69771369],
       [-12.29628667,  -8.67891142,  22.00149622]])