In [6]:
import numpy as np


### indexing a 1d array ###
arr = np.arange(0,11)
print("Original array:")
print(arr)

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10]


In [7]:
print(arr[1:5]) # one can slice and indexing just like a py list
print(arr[:6]) # one can slice and indexing just like a py list
print(arr[1:]) # one can slice and indexing just like a py list

[1 2 3 4]
[0 1 2 3 4 5]
[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
py_lst = [1,2,3,4,5,6]
print(py_lst[:4])

[1, 2, 3, 4]


In [9]:
arr = np.arange(0,11)
arr[0:5] = 100
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [10]:
arr = np.arange(0,11)
arr[:] = 8
print(arr)

[8 8 8 8 8 8 8 8 8 8 8]


In [12]:
arr = np.arange(0,11)
arr_copy = arr.copy()
arr[:] = 8
print("Notice how the numpy array changes:")
print(arr)
print('-------------------------------\n')
print("Notice how the numpy copy array DOES NOT change:")
print(arr_copy)
print('-------------------------------\n')

Notice how the numpy array changes:
[8 8 8 8 8 8 8 8 8 8 8]
-------------------------------

Notice how the numpy copy array DOES NOT change:
[ 0  1  2  3  4  5  6  7  8  9 10]
-------------------------------



In [14]:
### indexing a 2d array ###
arr_2df = np.array([[5,10,15],[20,25,30],[35,40,45]])
print(arr_2df)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [17]:
# grabing elements from a 2d array
print("Double bracket method:")
print(arr_2df[0][2])

Double bracket method:
15


In [18]:
print("Single bracket method (recommended):")
print(arr_2df[0,2])

Single bracket method (recommended):
15


In [19]:
# grabing chunks from a 2d array
print("Retrieving a matrix chuck:")
print(arr_2df[1:,:2])

Retrieving a matrix chuck:
[[20 25]
 [35 40]]


In [22]:
### conditional selection ###
arr = np.arange(1,11)
bool_arr = arr > 5

print("Conditional selection boll_arr:")
print(arr)
print(arr[arr > 5]) # acts as a filter
print(arr[arr < 5])
print(arr[bool_arr])
print('-------------------------------\n')

print("End of lecture exercise:")
arr = np.arange(50).reshape(5,10)
print(arr)
print(arr[arr > 25])
print(arr[arr < 25])
print(arr[3:,2:5])

Conditional selection boll_arr:
[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10]
[1 2 3 4]
[ 6  7  8  9 10]
-------------------------------

End of lecture exercise:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[32 33 34]
 [42 43 44]]
